[build]
  base    = "client"
  command = "npm run build"
  publish = "client/.next"

[functions]
  directory = "client/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
