[build]
  base = "client" # Ensure this is correct
  command = "npm run build && npm run export"
  publish = "out"


[functions]
  directory = "netlify/functions" # Adjust if using Netlify functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
